language: python
python:
- "3.4"
  
env:
  global:
    - DEPENDS = "numpy scipy matplotlib"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

virtualenv:
    system_site_packages: true

script: python pyclustering/ut/__init__.py