dist:       trusty
language:   python


os:
  - linux


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - python3


install:
  - sudo apt-get update
  - chmod u+x ci/travis-ci.sh
  - chmod u+x ci/travis-ci-deploy.sh


environment:
  access_token:
    secure: "CkWsTm14Emy0YneXlLuWOm8iWOlGVmYYNAdu0+oebuul34fXnhB63Fhq5aqIi6VwX8EA71ZkwcgnpQaKDzCKWL/u7IwPzu6wQcarxX6tET4rLj2dzQEFRBDmObPqSl73CnBBUxCGp4Ypc685QEZz2k3zMiGFR2zcx6TKg7TBiXivxITMy7OMR8b+il85oplBvF/Q8LL8kg8oU/KyW9BClHVeJfM0tlNKiZn4g2soiIQAIPz73xvyj/+NPVjYVrDTvtbJIa+DsZpwGEqZ4YIWXSj1SlX+XOg1LI2zO6JzK02yMKwnSCrMhwAXiLPjAOW7pNk2XqMtQVHJueo+QL30gdWh3DNR7seXkqptA/7pZsnjxl3MfRzoW673J04kkZZ/NDo384Es8xGLVeM2gjsKYgtV6fcx4RmKG9a4n7BT5skAt5HdHvAFcCfW5mLdBiSgK3K5n7j11USp++J9GKU7Qzz7Q073jnjtgGB3Rog1/uz3PJ96FyxqOUxw4pvqWJv4XiEyEuSK6JuCkUIyrtVVU5oglHgtetLO8kPlDIenj5ktE8su8BU9gAYXJ9pKSyOTewBykcfrGaUqeJ6D/Lo8N49NjhEkOAVhT1ZQ2UB41i0fn1mUeEWrv2gP1QI/MM3fVjyc01Wg7DDPfCl42i+/p8Vc2HKUUJyzOZnCbIm5goo="


stages:
  - build and test
  - deploy


jobs:
  include:
    - stage: build and test
      env: TITLE="Build CCORE."
      script: ./ci/travis-ci.sh BUILD_CCORE
    - stage: build and test
      env: TITLE="Run unit-tests for CCORE."
      script: ./ci/travis-ci.sh UT_CCORE
    - stage: build and test
      env: TITLE="Run memory leak analyser (valgrind) for CCORE."
      script: ./ci/travis-ci.sh VALGRIND_CCORE
    - stage: build and test
      env: TITLE="PyClustering unit and integration testing."
      script: ./ci/travis-ci.sh TEST_PYCLUSTERING
    - stage: build and test
      env: TITLE="Build documentation."
      script: ./ci/travis-ci.sh DOCUMENTATION
    - stage: deploy
      env: TITLE="Deploy CCORE"
      script: ./ci/travis-ci-deploy.sh