language: python
python:
- "3.4"

before_install:
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
  - pip install numpy
  - pip install matplotlib
  - pip install Pillow
  - python setup.py install

script: python pyclustering/ut/__init__.py