dist:       trusty
language:   python


os:
  - linux


addons:
  artifacts: true
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - python3


install:
  - sudo apt-get update
  - chmod u+x ci/travis-ci.sh


env:
  global:
    secure: "MegbZ1DpMKXx/lRQfPJjCeMWq21AJwB/9c0yEuTwGIHV7Uu4T4iQ/yrux3UmvJ64lnNqhr733LhM6ISSidoL5f/K6tBBpjzCgkGsu5ofmUHWjaai9NNcXEarOQH3xWSgtmBRNT8qOFwDTaU7HIeLu4mcKW8ixGZXbf6NNh0nlYyyg5D41fnGkHGekFX65kjJlRTORWNyw1+NlB9bqFvR1o6Be0towCbi05hIzOgeA44zkvm/hTtShQFrEIetchBCZiKv6HSsAptlAt7KKA/jlATt8ECzTBOAwS5/zDYVq1F50zvjaIw2k53CZg0xkJoIIJcFOjyNDwyDJwTLF+d4KIjlTHw1ip2Nb83EFsTJ874LySyiYngBCMSSR+0kJPRznidYa4T6w/LbBR87BsMkTnld3xQe84A3GuNZhRXmL+WWCHmmFWV2+CMV59TFKKLsP3/gjF0act3ZmfNk+r/7+buQXs490wbdWEEuOZCu37Yn+h2/yBpyije3K2QUD/ijZU2adxyNYhvFKB9U7FJNKBGXmlSt5y/C2XdpT8kvsV4N64OSVjnEGeR/pqBV41N1Tx1iEjJ9tRHnOJGpP0B/idCB8GPPIFXWAUlnVSXcuMAg4pGDhFacGIjlIJBo9kAtdUn9KCM1Sgjvf9gdv867UCvOrvpd/L+oLOsPkYY+yP0="


matrix:
  - env: CI_JOB=BUILD_CCORE
  - env: CI_JOB=UT_CCORE
  - env: CI_JOB=VALGRIND_CCORE
  - env: CI_JOB=TEST_PYCLUSTERING
  - env: CI_JOB=DOCUMENTATION


script:
  - ./ci/travis-ci.sh


after_success:
  - CI_JOB=DEPLOY
  - ./ci/travis-ci.sh