version: '{build}'


os:
  - Visual Studio 2015


init: []


environment:
  matrix:
  - PROJECT_TARGET: ccore
    PLATFORM: windows
  - PROJECT_TARGET: utcore
    PLATFORM: windows
  - PROJECT_TARGET: ccore
    PLATFORM: cygwin
    CYGWIN_PATH: C:\cygwin64\bin\bash


install:
  - IF "%PLATFORM%"=="cygwin" ( '%CYGWIN_PATH% -lc "cygcheck -dc cygwin"' )


build_script:
  - IF "%PLATFORM%"=="windows" ( msbuild ccore/ccore.sln /t:%PROJECT_TARGET%:Rebuild /p:configuration=Release )
  - IF "%PLATFORM%"=="cygwin" ( '%CYG_BASH% -lc "cd ccore; make ccore"' )


test_script:
  - IF "%PROJECT_TARGET%"=="utcore" ( IF "%PLATFORM%"=="windows" ( cd ccore\Release && utcore.exe ) )