version: '{build}'


os:
  - Visual Studio 2015


init: []


install: []


environment:
  matrix:
  - SOLUTION_TARGET: ccore\ccore.sln
  - SOLUTION_TARGET: ccore\utcore.sln


build_script:
  - msbuild %SOLUTION_TARGET% /p:configuration=Release


test_script:
  - IF "%SOLUTION_TARGET%"=="ccore\utcore.sln" ( cd ccore\Release && utcore.exe )