version: '{build}'


os:
  - Visual Studio 2015


init: []


install: []


environment:
  matrix:
  - CI_JOB: BUILD_CORE
  - CI_JOB: UT_CORE

 
build_script:
- ps: |
  if ($CI_JOB -eq "BUILD_CORE")
  {
    msbuild ccore\ccore.sln /p:configuration=Release
  }
  
  if ($CI_JOB -eq "UT_CORE")
  {
    msbuild ccore\utcore.sln /p:configuration=Release
  }


test_script:
- ps: |
  if ($CI_JOB -eq "BUILD_CORE")
  {
    return
  }
  
  if ($CI_JOB -eq "UT_CORE")
  {
    cd ccore
    return
  }
  