version: '{build}'


os:
  - Visual Studio 2015


init: []


environment:
  matrix:
  - PROJECT_TARGET: ccore
    PLATFORM_TARGET: windows
  - PROJECT_TARGET: utcore
    PLATFORM_TARGET: windows
  - PROJECT_TARGET: ccore
    PLATFORM_TARGET: cygwin
    CYGWIN_PATH: C:\cygwin64\bin\bash


install:
  - IF "%PLATFORM_TARGET%"=="cygwin" ( %CYGWIN_PATH% -lc "cygcheck -dc cygwin" )


build_script:
  - IF "%PLATFORM_TARGET%"=="windows" ( msbuild ccore/ccore.sln /t:%PROJECT_TARGET%:Rebuild /p:configuration=Release )
  - IF "%PLATFORM_TARGET%"=="cygwin" ( %CYGWIN_PATH% -lc "cd ccore; make ccore" )


test_script:
  - IF "%PROJECT_TARGET%"=="utcore" ( IF "%PLATFORM_TARGET%"=="windows" ( cd ccore\Release && utcore.exe ) )