version: '{build}'


os:
  - Visual Studio 2015


init: []


environment:
  CYGWIN_PATH: C:\cygwin64\bin\bash
  PYTHON_PATH: C:\Python34-x64
  MINICONDA_PATH: C:\Miniconda3-x64
  matrix:
  - CI_JOB: "BUILD_WINDOWS_CCORE"
  - CI_JOB: "UT_WINDOWS_CCORE"
  - CI_JOB: "BUILD_CYGWIN_CCORE"
  - CI_JOB: "UT_CYGWIN_CCORE"
  - CI_JOB: "PYCLUSTERING_WINDOWS"
  - CI_JOB: "PYCLUSTERING_CYGWIN"


build_script:
  - ps: ./ci/appveyor-ci.ps1 %CI_JOB%
