version: '{build}'


os:
  - Visual Studio 2015


init: []


environment:
  CYGWIN_PATH: C:\cygwin64\bin\bash
  PYTHON_PATH: C:\Python34-x64
  PYTHON_VERSION: 3.4
  MINICONDA_PATH: C:\Miniconda3-x64
  matrix:
  - PROJECT_TARGET: ccore
    PLATFORM_TARGET: windows
  - PROJECT_TARGET: utcore
    PLATFORM_TARGET: windows
  - PROJECT_TARGET: ccore
    PLATFORM_TARGET: cygwin
  - PROJECT_TARGET: ut
    PLATFORM_TARGET: cygwin


install:
  - IF "%PLATFORM_TARGET%"=="cygwin" ( 
      %CYGWIN_PATH% -lc "cygcheck -dc cygwin" 
    )


build_script:
  - IF "%PLATFORM_TARGET%"=="windows" (
      echo Build CCORE library using Microsoft Visual Studio for Windows platform.
      msbuild ccore/ccore.sln /t:%PROJECT_TARGET%:Rebuild /p:configuration=Release 
    )
  - IF "%PLATFORM_TARGET%"=="cygwin" (
      echo Build CCORE library using gcc for Cygwin platform.
      %CYGWIN_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; cd ccore; make %PROJECT_TARGET%" 
    )


test_script:
  - IF "%PROJECT_TARGET%"=="utcore" ( 
      IF "%PLATFORM_TARGET%"=="windows" ( 
        echo Run CCORE unit-tests for Windows platform.
        cd ccore\Release && utcore.exe 
      ) 
    )
  - IF "%PROJECT_TARGET%"=="ut" ( 
      IF "%PLATFORM_TARGET%"=="cygwin" (
        echo Run CCORE unit-tests for Cygwin platform.
        %CYGWIN_PATH% -lc "cd $APPVEYOR_BUILD_FOLDER; cd ccore; make utrun" 
      ) 
    )
