version: '{build}'


os:
  - Visual Studio 2015


init: []


install: []


environment:
  matrix:
  - PROJECT_TARGET: ccore
  - PROJECT_TARGET: utcore


build_script:
  - msbuild ccore.sln /t:%PROJECT_TARGET%:Build /p:configuration=Release


test_script:
  - IF "%PROJECT_TARGET%"=="ccore" ( cd ccore\Release && utcore.exe )