version: '{build}'


os:
  - Visual Studio 2015


init: []


install: []


environment:
  global:
  - CCORE_LIBRARY: ccore\src\ccore.vcxproj
  - CCORE_TESTS: ccore\tst\utcore.vcxproj

  matrix:
  - PROJECT_TARGET: "%CCORE_LIBRARY%"
  - PROJECT_TARGET: "%CCORE_TESTS%"


build_script:
  - msbuild %PROJECT_TARGET% /p:configuration=Release


test_script:
  - IF "%PROJECT_TARGET%"=="%CCORE_TESTS%" ( cd ccore\Release && utcore.exe )