version: '{build}'


os:
  - Visual Studio 2015


init: []


install: []


environment:
  matrix:
  - PROJECT_TARGET: ccore
  - PROJECT_TARGET: utcore


build_script:
  - msbuild ccore.sln /t:ccore:Rebuild /p:configuration=Release


test_script:
  - IF "%PROJECT_TARGET%"=="utcore" ( cd ccore\Release && utcore.exe )